- name: Setup
  hosts: all
  remote_user: ubuntu
  become: true
  become_method: sudo

  tasks:
  - name: Load Secret
    include_vars: secret.yaml

  - name: Install Sec Agent
    shell:
      cmd: ./security_agent_installer.sh --config security_agent_config.yaml --token "{{ my_secret }}"
