name: 'Ansible'
on:
    push:
      branches: [ master ]
    workflow_dispatch:

jobs:
    ansibleDeploy:
      runs-on: ubuntu-latest
      steps:
        - name: Add public IP to AWS security group
          uses: sohelamin/aws-security-group-add-ip-action@master
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: 'us-east-2'
            aws-security-group-id: ${{ secrets.AWS_SECURITY_GROUP_ID }}
            port: '22'
            to-port: '30'
            protocol: 'tcp'
            description: 'GitHub Action'
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Run Ansible Playbook
          run: cd infra/modules/ec2 && ansible-playbook playbook.yaml -i inventory --user ubuntu --key-file=ec2-key-home-task.pem
          