name: 'Terraform'

on:
  push:
    branches: [ "master" ]
  # workflow_dispatch:
  #   inputs:
  #     lintTerraform:
  #       description: 'Waiting for linting to succed'
  #       required: true

# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   AWS_REGION: us-east-2

jobs:

  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: SSh to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-217-121-53.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.PKEY }}
          port: 22
          script: |
            aws s3 ls

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: 1.0.6
      
      # - name: Terraform init
      #   id: init
      #   run: cd infra && terraform init
      
      # - name: Terraform Validate
      #   id: validate
      #   run: cd infra && terraform validate -no-color
      
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      #   run: cd infra && terraform apply -auto-approve -input=false


      # - name: Terraform destroy
      #   run: cd infra && terraform destroy