name: 'Terraform'

on:
  push:
    branches: [ "master" ]
  # workflow_dispatch:
  #   inputs:
  #     lintTerraform:
  #       description: 'Waiting for linting to succed'
  #       required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-2

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.6
      
      # - name: Terraform init
      #   id: init
      #   run: cd infra && terraform init
      
      # - name: Terraform Validate
      #   id: validate
      #   run: cd infra && terraform validate -no-color
      
      # - name: Terraform Apply
      #   uses: appleboy/ssh-action@master
      #   with:
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     port: ${{ secrets.PORT }}
      #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      #   run: cd infra && terraform apply -auto-approve -input=false


      - name: Terraform destroy
        run: cd infra && terraform destroy